# Generated by Django 4.2 on 2023-04-29 11:41

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 hour')),
                ('full_name', models.CharField(default='btc/tl::bitexen', max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=100)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatsAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='btc/tl::bitexen', max_length=100)),
                ('type', models.PositiveIntegerField(choices=[(1, 'DAILY'), (2, 'WEEKLY'), (3, 'MONTHLY')])),
                ('time', models.DateTimeField()),
                ('low', models.DecimalField(decimal_places=10, max_digits=100)),
                ('high', models.DecimalField(decimal_places=10, max_digits=100)),
                ('average', models.DecimalField(decimal_places=10, max_digits=100)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=100)),
            ],
            options={
                'index_together': {('full_name', 'type', 'time')},
            },
        ),
    ]
