# Generated by Django 4.2 on 2023-04-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsaggregation',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'HOURLY'), (1, 'DAILY'), (2, 'WEEKLY'), (3, 'MONTHLY')]),
        ),
    ]
