# Generated by Django 4.2 on 2023-04-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0004_alter_statsaggregation_index_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsaggregation',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
