# Generated by Django 4.2 on 2023-04-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0005_alter_statsaggregation_time'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='statsaggregation',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='statsaggregation',
            name='luigi_flag',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='statsaggregation',
            index_together={('full_name', 'type', 'time', 'luigi_flag')},
        ),
        migrations.RemoveField(
            model_name='statsaggregation',
            name='is_final',
        ),
    ]
